apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: mongodb
spec:
  selector:
    istio: ingressgateway
  servers:
    - hosts:
        - '*'
      port:
        name: tls-mongo
        number: 443
        protocol: TLS
      tls:
        credentialName: mongodb-cert
        mode: SIMPLE
