apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app: oauth-ingressgateway
    app.kubernetes.io/component: gateways
    app.kubernetes.io/instance: istio-system
    app.kubernetes.io/managed-by: maistra-istio-operator
    app.kubernetes.io/name: gateways
    app.kubernetes.io/part-of: istio
    chart: gateways
    heritage: Tiller
    istio: ingressgateway
    maistra.io/owner: istio-system
    release: istio
  name: api
spec:
  port:
    targetPort: oauth-http
  tls:
    termination: edge
  to:
    kind: Service
    name: oauth-ingressgateway
    weight: 100
  wildcardPolicy: None
