apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: api
spec:
  port:
    targetPort: oauth-http
  tls:
    termination: edge
  to:
    kind: Service
    name: oauth-ingressgateway
    weight: 100
  wildcardPolicy: None
