- name: Install Oauth2 Gateway Service Mesh Control Plane
  hosts: localhost
  gather_facts: no
  vars:
    - control_plane_namespace: istio-system
    - control_plane_src_dir: control-plane
    - redirect_url: https://api-istio-system.apps.cluster-77f0.77f0.sandbox1435.opentlc.com/oauth2/callback
    - oidc_issuer_url: https://dev-338970.okta.com/oauth2/default
    - cookie_secret: GRerqX0kInomjzMYFr50wA==
  tasks:


    - name: Get Current ServiceMeshMemberRoll
      k8s_info:
        api_version: maistra.io/v1
        name: default
        kind: ServiceMeshMemberRoll
        namespace: "{{ control_plane_namespace }}"
      register: roll_info
    - name: Debug member roll
      debug:
        var: roll_info
